stages:
  - claude

claude-code:
  stage: claude
  image: oven/bun:1
  before_script:
    - bun install
  rules:
    - if: $CI_MERGE_REQUEST_IID
  script:
    - bun run ./bin/claude-code-action.ts --provider gitlab --project-id $CI_PROJECT_ID \
      --mr-iid $CI_MERGE_REQUEST_IID --gitlab-host $CI_SERVER_URL
  variables:
    GITLAB_TOKEN: $GITLAB_TOKEN
    ANTHROPIC_API_KEY: $ANTHROPIC_API_KEY
